spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jackson.deserialization.fail-on-unknown-properties=true

# hibernate props
spring.jpa.hibernate.ddl-auto=validate

## JWT Properties
jwt.secret=${JWT_SECRET}